name: Update Repertorio

on:
  push:
    paths:
      - repertorio.json
      - '**/*.js'

jobs:
  update-repertorio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'CaioBarretoo'
          git config --global user.email 'caio.barret@hotmail.com'

      - name: Commit and push changes
        run: |
          git add repertorio.json
          git commit -m "Atualizando repertório" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
